### PR TITLE
Blog App - processing data in models

### PR DESCRIPTION
**Pull request by degisew**
### Blog App - processing data in models
**In this PR, I implemented the following features:**

- Created model classes for all entities as shown in the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).
- Set up associations between models.
- Created users.
- Created posts.
- Created comments.

Here is a link for the previous closed PR. [pull2](https://github.com/degisew/Blog-App/pull/2)

### CODE REVIEW

**Review by FrederickMih — COMMENTED** [review]
## Hi 🙋 @degisew  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

@degisew we make sure that the process of reviewing should be consistent hence you are not supposed to close a PR with comments from a reviewer. In case you close it because of any reason, kindly let us know in the summary of the new PR with a link to the closed PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by degisew** [comment]
Hello @FrederickMih 
Thanks for your comment. I suddenly merged the PR that's why I created another PR. but I will put the link to the closed one. Thanks again.

**Comment by degisew** [comment]
I attached the previous closed PR in the top documentation section.

**Review by Davidosky007 — APPROVED** [review]
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

* No linter errors 
* Well written PR description 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
